# Generated by Django 3.0.2 on 2020-03-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('percentage', models.IntegerField()),
                ('question_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
    ]
